// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwdnrc421dxVoQyNeLjsGPc41bCF0i_DI',
    appId: '1:534952957358:android:b03443ee09b7d768f2e43f',
    messagingSenderId: '534952957358',
    projectId: 'returnly-f592d',
    storageBucket: 'returnly-f592d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8_uXtwnO8E9RpWXae5L2SMtS6A64dMoA',
    appId: '1:534952957358:ios:6f0f3bb00d75a3d6f2e43f',
    messagingSenderId: '534952957358',
    projectId: 'returnly-f592d',
    storageBucket: 'returnly-f592d.firebasestorage.app',
    iosBundleId: 'com.example.returnly',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0_azSuBDKhIvHJ8a1rrEboKLAO8G84Og',
    appId: '1:534952957358:web:7d30886f4545f2f0f2e43f',
    messagingSenderId: '534952957358',
    projectId: 'returnly-f592d',
    authDomain: 'returnly-f592d.firebaseapp.com',
    storageBucket: 'returnly-f592d.firebasestorage.app',
    measurementId: 'G-K0N9R65K7Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8_uXtwnO8E9RpWXae5L2SMtS6A64dMoA',
    appId: '1:534952957358:ios:6f0f3bb00d75a3d6f2e43f',
    messagingSenderId: '534952957358',
    projectId: 'returnly-f592d',
    storageBucket: 'returnly-f592d.firebasestorage.app',
    iosBundleId: 'com.example.returnly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0_azSuBDKhIvHJ8a1rrEboKLAO8G84Og',
    appId: '1:534952957358:web:bddfda447f37224ef2e43f',
    messagingSenderId: '534952957358',
    projectId: 'returnly-f592d',
    authDomain: 'returnly-f592d.firebaseapp.com',
    storageBucket: 'returnly-f592d.firebasestorage.app',
    measurementId: 'G-HNQZ8LR8CR',
  );

}